<a href="https://colab.research.google.com/github/haridass2003/ppml/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[1, 2, 4], [5, 8, 7]])

print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [ ]:
# Creating a 3X4 array with all zeros
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Create a constant value array of complex type
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#Create a constant value array of complex type
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#Create an array with random values

d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.44003596 0.1895837 ]
 [0.95921821 0.68457856]]


In [ ]:
#Reshaping 3X4 array to 4X3 array

arr = np.array([[1, 2, 3, 4],

[5, 2, 4, 2],

[1, 2, 0, 1]])

newarr = arr.reshape(4, 3)

print ("\nOriginal array:\n", arr)

print ("Reshaped array[4,3]:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [ ]:
#Printing array dimensions (axes)

print("\nNo. of dimensions: ", arr.ndim)


No. of dimensions:  2


In [ ]:
# Printing shape of array
print("\nShape of array: ", arr.shape)


Shape of array:  (3, 4)


In [ ]:
# Printing size (total number of elements) of array
print("\nSize of array: ", arr.size)


Size of array:  12


In [ ]:
# Printing type of elements in array
print("\nArray stores elements of type: ",
arr.dtype)


Array stores elements of type:  int64


In [ ]:
# Flatten array

flarr = arr.flatten()

print ("\nOriginal array:\n", arr)

print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [ ]:
#converting datatypes from integer to float
newtype=arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32
