<a href="https://colab.research.google.com/github/haridass2003/ppml/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
# Slicing the Array
arr = np.array([[1, 2, 3, 4],
[5, 2, 4, 2],
[3, 5, 8, 9],
[5, 9, 2, 0],
[1, 2, 0, 1]])
print("every alternate row\n",arr[0:4:2])

every alternate row
 [[1 2 3 4]
 [3 5 8 9]]


In [ ]:
print("first 2 rows and 3 columns\n",arr[:2,:3])

first 2 rows and 3 columns
 [[1 2 3]
 [5 2 4]]


In [ ]:
print("except first 2 rows and 2columns\n",arr[2:,2:])

except first 2 rows and 2columns
 [[8 9]
 [2 0]
 [0 1]]


In [ ]:
print("extracting 2nd row, 3rd value\n",arr[2,3])
print("first 2 rows\n", arr[:2])

extracting 2nd row, 3rd value
 9
first 2 rows
 [[1 2 3 4]
 [5 2 4 2]]


In [ ]:
#original array
print("Original array:\n", arr)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [3 5 8 9]
 [5 9 2 0]
 [1 2 0 1]]


In [ ]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
"(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4 4 5 5]


In [ ]:
# boolean array indexing example
cond = arr > 2
# cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 2:\n",
temp)


Elements greater than 2:
 [3 4 5 4 3 5 8 9 5 9]


In [ ]:
#joining two array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [ ]:
#Horizontal join
arr = np.hstack((arr1, arr2))
print("\horizontal joining:\n",arr)

\horizontal joining:
 [1 2 3 4 5 6]


In [ ]:
#Vertical join
print("\nOriginal arrays:\n",arr1,arr2)

arr = np.vstack((arr1, arr2))
print("\nVertical joining:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#Splitting array
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print("\nOriginal Array:\n",arr)
print("\nSplitted array:\n",newarr)


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Displaying split array in another form
print("\nSplit array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Split array in another form:

[1 2]
[3 4]
[5 6]


In [ ]:
#indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print("Original array:",arr)
x = np.where(arr == 4)
print("\nIndexes where the value is 4:",x)

Original array: [1 2 3 4 5 4 4]

Indexes where the value is 4: (array([3, 5, 6]),)


In [ ]:
#Sorting the array
arr = np.array([3, 2, 0, 1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))


Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [ ]:
#Filter
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]
